version: '3.8'

services:
  # Sistema RSCA Principal (preservando atual)
  rsca-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: rsca-main
    ports:
      - "8501:8501"  # Streamlit Dashboard
      - "8080:8080"  # API REST (futuro)
    environment:
      # Configurações atuais preservadas
      - OLLAMA_HOST=http://ollama:11434
      - NEO44J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=rsca_secure_2025
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      # Modo híbrido: YAML + GraphRAG
      - STORAGE_MODE=hybrid
      - ENABLE_GRAPHRAG=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs  
      - ./reflection:/app/reflection  # Preservar estados YAML
      - ./exports:/app/exports
    depends_on:
      - neo4j
      - chromadb
      - ollama
    restart: unless-stopped

  # Ollama para LLMs Locais (configuração atual preservada)
  ollama:
    image: ollama/ollama:latest
    container_name: rsca-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  # Neo4j para GraphRAG (NOVO)
  neo4j:
    image: neo4j:5.15-community
    container_name: rsca-neo4j
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/rsca_secure_2025
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial_size=512m
      - NEO4J_dbms_memory_heap_max_size=2g
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./infrastructure/neo4j/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # ChromaDB para Vector Search (NOVO)
  chromadb:
    image: chromadb/chroma:latest
    container_name: rsca-chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.token.TokenAuthCredentialsProvider
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=X-Chroma-Token
      - CHROMA_AUTH_TOKEN_SECRET=rsca_chroma_secret_2025
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  chromadb_data:
  ollama_data:
